name: continuous-integration/gh-actions/gui

on: [push, pull_request]

jobs:
  build-macos:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: update brew and install dependencies
      run: brew update && brew install boost hidapi zmq libpgm miniupnpc ldns expat libunwind-headers protobuf qt5
    - name: downgrade boost to version 1.60
      run: brew install boost@1.60 && brew link boost@1.60 --overwrite --force
    - name: build
      run: export PATH=$PATH:/usr/local/opt/qt/bin && ./build.sh
    - name: test qml
      run: build/release/bin/bittube-wallet-gui.app/Contents/MacOS/bittube-wallet-gui --test-qml

  build-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: remove bundled boost
      run: sudo rm -rf /usr/local/share/boost
    - name: set apt conf
      run: |
        echo "Acquire::Retries \"3\";" | sudo tee -a /etc/apt/apt.conf.d/80-custom
        echo "Acquire::http::Timeout \"120\";" | sudo tee -a /etc/apt/apt.conf.d/80-custom
        echo "Acquire::ftp::Timeout \"120\";" | sudo tee -a /etc/apt/apt.conf.d/80-custom
    - name: update apt
      run: sudo apt update
    - name: install bittube dependencies
      run: sudo apt -y install build-essential cmake libboost-all-dev miniupnpc libunbound-dev graphviz doxygen libunwind8-dev pkg-config libssl-dev libzmq3-dev libsodium-dev libhidapi-dev libnorm-dev libusb-1.0-0-dev libpgm-dev
    - name: install bittube gui dependencies
      run: sudo apt -y install qtbase5-dev qt5-default qtdeclarative5-dev qml-module-qtquick-controls qml-module-qtquick-controls2 qml-module-qtquick-dialogs qml-module-qtquick-xmllistmodel qml-module-qt-labs-settings qml-module-qt-labs-folderlistmodel qttools5-dev-tools qml-module-qtquick-templates2 libqt5svg5-dev xvfb
    - name: build
      run: ./build.sh
    - name: test qml
      run: xvfb-run -a build/release/bin/bittube-wallet-gui --test-qml

  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - uses: eine/setup-msys2@v0
      with:
        update: true
    - name: install bittube dependencies
      run: msys2do pacman -S --noconfirm mingw-w64-x86_64-toolchain make mingw-w64-x86_64-cmake mingw-w64-x86_64-boost mingw-w64-x86_64-openssl mingw-w64-x86_64-zeromq mingw-w64-x86_64-libsodium mingw-w64-x86_64-hidapi mingw-w64-x86_64-protobuf-c mingw-w64-x86_64-libusb git mingw-w64-x86_64-qt5
    - name: downgrade boost to version 1.72
      run: msys2do pacman -U --noconfirm http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-boost-1.72.0-3-any.pkg.tar.zst
    - name: disable qtquickcompiler
      run: msys2do sed -i s/CONFIG\ +=\ qtquickcompiler// bittube-wallet-gui.pro
    - name: build
      run: msys2do ./build.sh release
    - name: test qml
      run: msys2do build/release/bin/bittube-wallet-gui --test-qml
